LIDAR = ["LIDAR", 370]
LIDAR_CONV = ["LIDAR_conv", 360]
ROTATION = ["rotation", 2]
TARGET_ANGLE = ["target_angle", 2]
VELOCITY = ["velocity", 1]
DISTANCE = ["distance", 1]
DISTANCE_VEC = ["distance_vec", 2]
POSITION = ["position", 2]
